amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.2
    update_min_a: 0.2
    resample_interval: 1
    transform_tolerance: 1.0
    laser_min_range: 0.1
    laser_max_range: 3.5
    laser_model_type: likelihood_field
    odom_frame_id: odom
    base_frame_id: base_link
    global_frame_id: map
    scan_topic: scan
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0

