planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      use_astar: false
      allow_unknown: false
      tolerance: 1.0

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      critics: ["GoalDistCritic", "GoalAlignCritic", "PathDistCritic", "PathAlignCritic",
                "OscillationCritic", "ObstacleFootprintCritic", "BaseObstacleCritic"]
      path_distance_bias: 32.0
      goal_distance_bias: 24.0
      occdist_scale: 0.01
      forward_point_distance: 0.325
      local_costmap: "local_costmap"
      
global_costmap:
  ros__parameters:
    global_frame: "map"
    robot_base_frame: "base_link"
    update_frequency: 5.0
    publish_frequency: 1.0
    rolling_window: false
    width: 10.0
    height: 10.0
    resolution: 0.05
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: True
      enabled: true
      subscribe_to_updates: true
      transform_tolerance: 0.1
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      observation_sources: "laser"
      laser:
        sensor_frame: "laser_frame"
        data_type: "LaserScan"
        topic: "/scan"
        expected_update_rate: 20.0
        observation_persistence: 0.5
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.3
      enabled: true
      observation_sources: "scan"
      scan:
          topic: /scan
          obstacle_max_range: 2.5
          obstacle_min_range: 0.3
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          inf_is_valid: false

local_costmap:
  ros__parameters:
    global_frame: "odom"   # local costmap commonly uses odom
    robot_base_frame: "base_link"
    update_frequency: 10.0
    publish_frequency: 1.0
    rolling_window: true
    width: 6.0
    height: 6.0
    resolution: 0.05
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: "laser"
      laser:
        sensor_frame: "laser_frame"
        data_type: "LaserScan"
        topic: "/scan"
        expected_update_rate: 20.0
        observation_persistence: 0.5
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.3



